hugo new content content/buildings/Catnip_Field.md
hugo new content content/buildings/Pasture.md
hugo new content content/buildings/Solar_Farm.md
hugo new content content/buildings/Aqueduct.md
hugo new content content/buildings/Hydro_Plant.md
hugo new content content/buildings/Hut.md
hugo new content content/buildings/Log_House.md
hugo new content content/buildings/Mansion.md
hugo new content content/buildings/Library.md
hugo new content content/buildings/Data_Center.md
hugo new content content/buildings/Academy.md
hugo new content content/buildings/Observatory.md
hugo new content content/buildings/Bio_Lab.md
hugo new content content/buildings/Barn.md
hugo new content content/buildings/Warehouse.md
hugo new content content/buildings/Harbour.md
hugo new content content/buildings/Mine.md
hugo new content content/buildings/Quarry.md
hugo new content content/buildings/Smelter.md
hugo new content content/buildings/Calciner.md
hugo new content content/buildings/Steamworks.md
hugo new content content/buildings/Magneto.md
hugo new content content/buildings/Lumber_Mill.md
hugo new content content/buildings/Oil_Well.md
hugo new content content/buildings/Workshop.md
hugo new content content/buildings/Factory.md
hugo new content content/buildings/Reactor.md
hugo new content content/buildings/Accelerator.md
hugo new content content/buildings/Tradepost.md
hugo new content content/buildings/Mint.md
hugo new content content/buildings/Brewery.md
hugo new content content/buildings/Amphitheatre.md
hugo new content content/buildings/Broadcast_Tower.md
hugo new content content/buildings/Chapel.md
hugo new content content/buildings/Temple.md
hugo new content content/buildings/Unic._Pasture.md
hugo new content content/buildings/Ziggurat.md
hugo new content content/buildings/Chronosphere.md
hugo new content content/buildings/AI_Core.md
hugo new content content/buildings/Zebra_Outpost.md
hugo new content content/buildings/Zebra_Workshop.md
hugo new content content/buildings/Zebra_Forge.md
hugo new content content/buildings/Ivory_Temple.md
hugo new content content/techs/Calendar.md
hugo new content content/techs/Agriculture.md
hugo new content content/techs/Archery.md
hugo new content content/techs/Mining.md
hugo new content content/techs/Metal_Working.md
hugo new content content/techs/Animal_Husbandry.md
hugo new content content/techs/Civil_Service.md
hugo new content content/techs/Mathematics.md
hugo new content content/techs/Construction.md
hugo new content content/techs/Engineering.md
hugo new content content/techs/Currency.md
hugo new content content/techs/Writing.md
hugo new content content/techs/Philosophy.md
hugo new content content/techs/Machinery.md
hugo new content content/techs/Steel.md
hugo new content content/techs/Theology.md
hugo new content content/techs/Astronomy.md
hugo new content content/techs/Navigation.md
hugo new content content/techs/Architecture.md
hugo new content content/techs/Physics.md
hugo new content content/techs/Metaphysics.md
hugo new content content/techs/Chemistry.md
hugo new content content/techs/Acoustics.md
hugo new content content/techs/Drama_and_Poetry.md
hugo new content content/techs/Geology.md
hugo new content content/techs/Electricity.md
hugo new content content/techs/Biology.md
hugo new content content/techs/Biochemistry.md
hugo new content content/techs/Genetics.md
hugo new content content/techs/Industrialization.md
hugo new content content/techs/Mechanization.md
hugo new content content/techs/Metallurgy.md
hugo new content content/techs/Combustion.md
hugo new content content/techs/Ecology.md
hugo new content content/techs/Electronics.md
hugo new content content/techs/Robotics.md
hugo new content content/techs/Artificial_Intelligence.md
hugo new content content/techs/Quantum_Cryptography.md
hugo new content content/techs/Blackchain.md
hugo new content content/techs/Nuclear_Fission.md
hugo new content content/techs/Rocketry.md
hugo new content content/techs/Oil_Processing.md
hugo new content content/techs/Satellites.md
hugo new content content/techs/Orbital_Engineering.md
hugo new content content/techs/Thorium.md
hugo new content content/techs/Exogeology.md
hugo new content content/techs/Advanced_Exogeology.md
hugo new content content/techs/Nanotechnology.md
hugo new content content/techs/Superconductors.md
hugo new content content/techs/Antimatter.md
hugo new content content/techs/Terraformation.md
hugo new content content/techs/Hydroponics.md
hugo new content content/techs/Exophysics.md
hugo new content content/techs/Particle_Physics.md
hugo new content content/techs/Dimensional_Physics.md
hugo new content content/techs/Artificial_Gravity.md
hugo new content content/techs/Chronophysics.md
hugo new content content/techs/Tachyon_Theory.md
hugo new content content/techs/Cryptotheology.md
hugo new content content/techs/Void_Space.md
hugo new content content/techs/Paradox_Theory.md
hugo new content content/Policy/Liberty.md
hugo new content content/Policy/Tradition.md
hugo new content content/Policy/Monarchy.md
hugo new content content/Policy/Autocracy.md
hugo new content content/Policy/Republic.md
hugo new content content/Policy/Socialism.md
hugo new content content/Policy/Liberalism.md
hugo new content content/Policy/Communism.md
hugo new content content/Policy/Fascism.md
hugo new content content/Policy/Technocracy.md
hugo new content content/Policy/Order_of_the_Stars.md
hugo new content content/Policy/Cosmological_Libertarianism.md
hugo new content content/Policy/Transkittenism.md
hugo new content content/Policy/Necrocracy.md
hugo new content content/Policy/Radical_Xenophobia.md
hugo new content content/Policy/Diplomacy.md
hugo new content content/Policy/Isolationism.md
hugo new content content/Policy/Zebra_Relations:_Appeasement.md
hugo new content content/Policy/Zebra_Relations:_Bellicosity.md
hugo new content content/Policy/Knowledge_Sharing.md
hugo new content content/Policy/Cultural_Exchange.md
hugo new content content/Policy/Big_Stick_Policy.md
hugo new content content/Policy/City_On_A_Hill.md
hugo new content content/Policy/Outer_Space_Treaty.md
hugo new content content/Policy/Militarize_Space.md
hugo new content content/Policy/Stoicism.md
hugo new content content/Policy/Epicurianism.md
hugo new content content/Policy/Carnivale.md
hugo new content content/Policy/Extravagance.md
hugo new content content/Policy/Rationing.md
hugo new content content/Policy/Frugality.md
hugo new content content/Policy/Rationality.md
hugo new content content/Policy/Mysticism.md
hugo new content content/Policy/Strip_Mining.md
hugo new content content/Policy/Clear_Cutting.md
hugo new content content/Policy/Environmentalism.md
hugo new content content/Policy/Sustainability.md
hugo new content content/Policy/Full_Industrialization.md
hugo new content content/Policy/Conservation.md
hugo new content content/Policy/Open_Woodlands.md
hugo new content content/Policy/Immortalism.md
hugo new content content/Policy/Space_expansionism.md
hugo new content content/Policy/Siphoning.md
hugo new content content/religion/Solarchant.md
hugo new content content/religion/Scholasticism.md
hugo new content content/religion/Golden_Spire.md
hugo new content content/religion/Sun_Altar.md
hugo new content content/religion/Stained_Glass.md
hugo new content content/religion/Solar_Revolution.md
hugo new content content/religion/Basilica.md
hugo new content content/religion/Templars.md
hugo new content content/religion/Apocripha.md
hugo new content content/religion/Transcendence.md
hugo new content content/ziggurat/Unicorn_Tomb.md
hugo new content content/ziggurat/Ivory_Tower.md
hugo new content content/ziggurat/Ivory_Citadel.md
hugo new content content/ziggurat/Sky_Palace.md
hugo new content content/ziggurat/Unicorn_Utopia.md
hugo new content content/ziggurat/Sunspire.md
hugo new content content/ziggurat/Marker.md
hugo new content content/ziggurat/Unicorn_Graveyard.md
hugo new content content/ziggurat/Unicorn_Necropolis.md
hugo new content content/ziggurat/Black_Pyramid.md
hugo new content content/transcendence/Black_Obelisk.md
hugo new content content/transcendence/Black_Nexus.md
hugo new content content/transcendence/Black_Core.md
hugo new content content/transcendence/Singularity.md
hugo new content content/transcendence/Black_Library.md
hugo new content content/transcendence/Black_Radiance.md
hugo new content content/transcendence/Blazar.md
hugo new content content/transcendence/Dark_Nova.md
hugo new content content/transcendence/Mausoleum.md
hugo new content content/transcendence/Holy_Genocide.md
hugo new content content/space/Orbital_Launch.md
hugo new content content/space/Moon_Mission.md
hugo new content content/space/Dune_Mission.md
hugo new content content/space/Piscine_Mission.md
hugo new content content/space/Helios_Mission.md
hugo new content content/space/T-minus_Mission.md
hugo new content content/space/Kairo_Mission.md
hugo new content content/space/Rorschach.md
hugo new content content/space/Yarn_Mission.md
hugo new content content/space/Umbra_Mission.md
hugo new content content/space/Charon_Mission.md
hugo new content content/space/Centaurus_System_Mission.md
hugo new content content/space/Furthest_Ring.md
hugo new content content/planet/Cath.md
hugo new content content/planet/Redmoon.md
hugo new content content/planet/Dune.md
hugo new content content/planet/Piscine.md
hugo new content content/planet/Helios.md
hugo new content content/planet/T-Minus.md
hugo new content content/planet/Kairo.md
hugo new content content/planet/Yarn.md
hugo new content content/planet/Umbra.md
hugo new content content/planet/Charon.md
hugo new content content/planet/Centaurus_System.md
hugo new content content/planet/Furthest_Ring.md
hugo new content content/job/Woodcutter.md
hugo new content content/job/Farmer.md
hugo new content content/job/Scholar.md
hugo new content content/job/Hunter.md
hugo new content content/job/Miner.md
hugo new content content/job/Priest.md
hugo new content content/job/Geologist.md
hugo new content content/job/Engineer.md
hugo new content content/craft/Refine_Catnip.md
hugo new content content/craft/Wooden_Beam.md
hugo new content content/craft/Stone_Slab.md
hugo new content content/craft/Metal_Plate.md
hugo new content content/craft/Steel.md
hugo new content content/craft/Concrete.md
hugo new content content/craft/Gear.md
hugo new content content/craft/Alloy.md
hugo new content content/craft/Eludium.md
hugo new content content/craft/Scaffold.md
hugo new content content/craft/Trade_Ship.md
hugo new content content/craft/Tanker.md
hugo new content content/craft/Kerosene.md
hugo new content content/craft/Parchment.md
hugo new content content/craft/Manuscript.md
hugo new content content/craft/Compendium.md
hugo new content content/craft/Blueprint.md
hugo new content content/craft/Thorium.md
hugo new content content/craft/Megalith.md
hugo new content content/craft/Bloodstone.md
hugo new content content/craft/T-Mythril.md
hugo new content content/upgrade/Mineral_Hoes.md
hugo new content content/upgrade/Iron_Hoes.md
hugo new content content/upgrade/Mineral_Axe.md
hugo new content content/upgrade/Iron_Axe.md
hugo new content content/upgrade/Steel_Axe.md
hugo new content content/upgrade/Reinforced_Saw.md
hugo new content content/upgrade/Steel_Saw.md
hugo new content content/upgrade/Titanium_Saw.md
hugo new content content/upgrade/Alloy_Saw.md
hugo new content content/upgrade/Titanium_Axe.md
hugo new content content/upgrade/Alloy_Axe.md
hugo new content content/upgrade/Unobtainium_Axe.md
hugo new content content/upgrade/Unobtainium_Saw.md
hugo new content content/upgrade/Expanded_Barns.md
hugo new content content/upgrade/Reinforced_Barns.md
hugo new content content/upgrade/Reinforced_Warehouses.md
hugo new content content/upgrade/Titanium_Barns.md
hugo new content content/upgrade/Alloy_Barns.md
hugo new content content/upgrade/Concrete_Barns.md
hugo new content content/upgrade/Titanium_Warehouses.md
hugo new content content/upgrade/Alloy_Warehouses.md
hugo new content content/upgrade/Concrete_Warehouses.md
hugo new content content/upgrade/Storage_Bunkers.md
hugo new content content/upgrade/Energy_Rifts.md
hugo new content content/upgrade/Stasis_Chambers.md
hugo new content content/upgrade/Void_Energy.md
hugo new content content/upgrade/Dark_Energy.md
hugo new content content/upgrade/Chronoforge.md
hugo new content content/upgrade/Tachyon_Accelerators.md
hugo new content content/upgrade/Flux_Condensator.md
hugo new content content/upgrade/LHC.md
hugo new content content/upgrade/Photovoltaic_Cells.md
hugo new content content/upgrade/Thin_Film_Cells.md
hugo new content content/upgrade/Quantum_Dot_Cells.md
hugo new content content/upgrade/Solar_Satellites.md
hugo new content content/upgrade/Expanded_Cargo.md
hugo new content content/upgrade/Barges.md
hugo new content content/upgrade/Reactor_Vessel.md
hugo new content content/upgrade/Ironwood_Huts.md
hugo new content content/upgrade/Concrete_Huts.md
hugo new content content/upgrade/Unobtainium_Huts.md
hugo new content content/upgrade/Eludium_Huts.md
hugo new content content/upgrade/Silos.md
hugo new content content/upgrade/Refrigeration.md
hugo new content content/upgrade/Composite_Bow.md
hugo new content content/upgrade/Crossbow.md
hugo new content content/upgrade/Railgun.md
hugo new content content/upgrade/Bolas.md
hugo new content content/upgrade/Hunting_Armour.md
hugo new content content/upgrade/Steel_Armour.md
hugo new content content/upgrade/Alloy_Armour.md
hugo new content content/upgrade/Nanosuits.md
hugo new content content/upgrade/Caravanserai.md
hugo new content content/upgrade/Catnip_Enrichment.md
hugo new content content/upgrade/Gold_Ore.md
hugo new content content/upgrade/Geodesy.md
hugo new content content/upgrade/Register.md
hugo new content content/upgrade/Concrete_Pillars.md
hugo new content content/upgrade/Mining_Drill.md
hugo new content content/upgrade/Unobtainium_Drill.md
hugo new content content/upgrade/Coal_Furnace.md
hugo new content content/upgrade/Deep_Mining.md
hugo new content content/upgrade/Pyrolysis.md
hugo new content content/upgrade/Electrolytic_Smelting.md
hugo new content content/upgrade/Oxidation.md
hugo new content content/upgrade/Steel_Plants.md
hugo new content content/upgrade/Automated_Plants.md
hugo new content content/upgrade/Nuclear_Plants.md
hugo new content content/upgrade/Rotary_Kiln.md
hugo new content content/upgrade/Fluidized_Reactors.md
hugo new content content/upgrade/Nuclear_Smelters.md
hugo new content content/upgrade/Orbital_Geodesy.md
hugo new content content/upgrade/Printing_Press.md
hugo new content content/upgrade/Offset_Press.md
hugo new content content/upgrade/Photolithography.md
hugo new content content/upgrade/Uplink.md
hugo new content content/upgrade/Starlink.md
hugo new content content/upgrade/Cryocomputing.md
hugo new content content/upgrade/Machine_Learning.md
hugo new content content/upgrade/Workshop_Automation.md
hugo new content content/upgrade/Advanced_Automation.md
hugo new content content/upgrade/Pneumatic_Press.md
hugo new content content/upgrade/High_Pressure_Engine.md
hugo new content content/upgrade/Fuel_Injectors.md
hugo new content content/upgrade/Factory_Logistics.md
hugo new content content/upgrade/Carbon_Sequestration.md
hugo new content content/upgrade/Factory_Optimization.md
hugo new content content/upgrade/Factory_Robotics.md
hugo new content content/upgrade/Space_Engineers.md
hugo new content content/upgrade/AI_Engineers.md
hugo new content content/upgrade/Chronoengineers.md
hugo new content content/upgrade/Space_Manufacturing.md
hugo new content content/upgrade/Celestial_Mechanics.md
hugo new content content/upgrade/Astrolabe.md
hugo new content content/upgrade/Titanium_Reflectors.md
hugo new content content/upgrade/Unobtainium_Reflectors.md
hugo new content content/upgrade/Eludium_Reflectors.md
hugo new content content/upgrade/Hydro_Plant_Turbines.md
hugo new content content/upgrade/Antimatter_Bases.md
hugo new content content/upgrade/AI_Bases.md
hugo new content content/upgrade/Antimatter_Fission.md
hugo new content content/upgrade/Antimatter_Reactors.md
hugo new content content/upgrade/Advanced_AM_Reactors.md
hugo new content content/upgrade/Void_Reactors.md
hugo new content content/upgrade/Relic_Station.md
hugo new content content/upgrade/Antimatter_Drive.md
hugo new content content/upgrade/Pumpjack.md
hugo new content content/upgrade/Biofuel_Processing.md
hugo new content content/upgrade/Unicorn_Selection.md
hugo new content content/upgrade/GM_Catnip.md
hugo new content content/upgrade/CAD_System.md
hugo new content content/upgrade/SETI.md
hugo new content content/upgrade/Logistics.md
hugo new content content/upgrade/Augmentations.md
hugo new content content/upgrade/Telecommunication.md
hugo new content content/upgrade/Neural_Networks.md
hugo new content content/upgrade/Robotic_Assistance.md
hugo new content content/upgrade/Enriched_Uranium.md
hugo new content content/upgrade/Cold_Fusion.md
hugo new content content/upgrade/Thorium_Reactors.md
hugo new content content/upgrade/Enriched_Thorium.md
hugo new content content/upgrade/Hubble_Space_Telescope.md
hugo new content content/upgrade/Satellite_Navigation.md
hugo new content content/upgrade/Satellite_Radio.md
hugo new content content/upgrade/Astrophysicists.md
hugo new content content/upgrade/Microwarp_Reactors.md
hugo new content content/upgrade/Planet_Busters.md
hugo new content content/upgrade/Thorium_Drive.md
hugo new content content/upgrade/Spice_Navigation.md
hugo new content content/upgrade/Long-range_Spaceships.md
hugo new content content/upgrade/Oil_Refinery.md
hugo new content content/upgrade/Oil_Distillation.md
hugo new content content/upgrade/Factory_Processing.md
hugo new content content/upgrade/Void_Aspiration.md
hugo new content content/upgrade/Distortion.md
hugo new content content/upgrade/Chronosurge.md
hugo new content content/upgrade/Invisible_Black_Hand.md
hugo new content content/zebraUpgrades/Dark_Revolution.md
hugo new content content/zebraUpgrades/Dark_Brew.md
hugo new content content/zebraUpgrades/Whispers.md
hugo new content content/zebraUpgrades/Minerology_department.md
hugo new content content/zebraUpgrades/Bloodstone_Institute.md
